rules_folder: /opt/rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: 10.0.5.4
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2
smtp_host: smtp.sendgrid.net
smtp_auth_file: /opt/config/smtp_auth_file.yaml
email_reply_to: foram.kapadia@apitutdelabs.com
from_addr: bot@elastalert.internal.aptitudelabs.com
