rules_folder: /opt/rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: internal-es-01.ip
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2
smtp_host: email-smtp.us-east-1.amazonaws.com
smtp_auth_file: /opt/config/smtp_auth_file.yaml
email_reply_to: ashishn@yashsolutions.com
from_addr: ashishn@yashsolutions.com
